/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apidemo;

import apidemo.util.VerticalPanel;
import java.awt.BorderLayout;
import javax.swing.JTextField;
import javax.swing.JPanel;
/**
 *
 * @author nick
 */
public class VixHedgePanel extends JPanel {
    
    // srike price
    // up threshold
    // down threshold
    // future long/short (exist)
    // future price (exist)
    private final JTextField m_strikePrice = new JTextField(7);
    private final JTextField m_upThreshold = new JTextField(7);
    private final JTextField m_downThreshold = new JTextField(7);
    private final JTextField m_futureLongShort = new JTextField(7);
    private final JTextField m_futurePrice = new JTextField(7);
    
    /**
     * Creates new form VixHedgePanel
     */
    public VixHedgePanel() {
        initComponents();
        
        JPanel p1 = new VerticalPanel();
        p1.add("Strike Pirce", m_strikePrice);
        
        this.add(p1, BorderLayout.NORTH);
        
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
